quarkus.http.port=8080

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/unifor_db
quarkus.datasource.username=unifor
quarkus.datasource.password=unifor
quarkus.hibernate-orm.database.generation=update

# Keycloak (OIDC)
quarkus.oidc.auth-server-url=http://keycloak:8080/realms/unifor
quarkus.oidc.client-id=unifor-backend
quarkus.oidc.credentials.secret=backend-secret
quarkus.oidc.application-type=service
quarkus.oidc.roles.source=realm
quarkus.oidc.token.audience-check-enabled=false

# CORS (para o Angular)
quarkus.http.cors=true
quarkus.http.cors.origins=*
